general.import = ["~/.config/alacritty/aura-theme.toml"]

[font]
size = 14

[font.bold]
family = "Ubuntu Mono"
style = "Bold"

[font.bold_italic]
family = "Ubuntu Mono"
style = "Bold Italic"

[font.italic]
family = "Ubuntu Mono"
style = "Italic"

[font.normal]
family = "Ubuntu Mono"
style = "Regular"
